name: Build MSIX

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-msix:
    runs-on: windows-2022

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Get packages
        run: flutter pub get

      - name: Create missing platform folders
        run: flutter create . --platforms=windows

      - name: Build Windows release
        run: flutter build windows --release

      - name: Create MSIX package
        run: dart run msix:create

      - name: Upload MSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-bmi-analyzer-msix
          path: build/windows/x64/runner/Release/*.msix
